#!/bin/bash

Version=$(grep 'version=' /usr/ports/kernel/linux-stable/Pkgfile | cut --delimiter='=' --field=2)

ln -sd  /usr/src/linux-${Version} /lib/modules/${Version}/build
ln -sd  /usr/src/linux-${Version} /lib/modules/${Version}/source

#kexec -l /boot/vmlinuz-$Version --append=root=/dev/sda3
grub-mkconfig -o /boot/grub/grub.cfg
